# Generated by Django 5.2.4 on 2025-07-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnciclopediaAttacchi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_attacco', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('livello_rischio', models.CharField(choices=[('basso', 'Basso'), ('medio', 'Medio'), ('alto', 'Alto')], default='basso', max_length=50)),
                ('contromisure', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessaggioSospetto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testo', models.TextField()),
                ('data_ricezione', models.DateTimeField(auto_now_add=True)),
                ('mittente', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroTelefonico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('operatore', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('mobile', 'Mobile'), ('fisso', 'Fisso')], default='mobile', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RilevamentoAttacco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=255)),
                ('domande', models.TextField()),
                ('numero_domande', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('tipo_utente', models.CharField(choices=[('privato', 'Privato'), ('azienda', 'Aziendale')], default='azienda', max_length=50)),
                ('nome_azienda', models.CharField(blank=True, max_length=100, null=True)),
                ('ruolo', models.CharField(max_length=50)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('eta', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RichiestaAnalisi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_richiesta', models.DateTimeField(auto_now_add=True)),
                ('ora_richiesta', models.TimeField()),
                ('esito', models.TextField()),
                ('messaggio_sospetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.messaggiosospetto')),
                ('numero_telefonico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.numerotelefonico')),
            ],
        ),
        migrations.CreateModel(
            name='Pdfreport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_file', models.CharField(max_length=255)),
                ('contenuto', models.TextField()),
                ('data_generazione', models.DateTimeField(auto_now_add=True)),
                ('ora_generazione', models.TimeField()),
                ('dimensione', models.IntegerField()),
                ('rilevamento_attacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.rilevamentoattacco')),
            ],
        ),
        migrations.CreateModel(
            name='Esecuzione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_esecuzione', models.DateTimeField(auto_now_add=True)),
                ('ora_esecuzione', models.TimeField()),
                ('rilevamento_attacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.rilevamentoattacco')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.utente')),
            ],
        ),
    ]
