# Generated by Django 5.2.4 on 2025-07-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enciclopediaattacchi',
            name='livello_rischio',
            field=models.CharField(choices=[('basso', 'Basso'), ('medio', 'Medio'), ('alto', 'Alto')], default='basso', max_length=100),
        ),
    ]
