# Generated by Django 5.2.4 on 2025-07-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0003_alter_enciclopediaattacchi_livello_rischio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enciclopediaattacchi',
            name='livello_rischio',
            field=models.CharField(choices=[('basso', 'Basso'), ('medio', 'Medio'), ('alto', 'Alto')], default='basso', max_length=100),
        ),
        migrations.AlterField(
            model_name='utente',
            name='eta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
