# Generated by Django 5.2.4 on 2025-07-21 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0004_alter_enciclopediaattacchi_livello_rischio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enciclopediaattacchi',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.utente'),
        ),
    ]
