# Generated by Django 5.2.4 on 2025-07-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0005_enciclopediaattacchi_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esecuzione',
            name='rilevamento_attacco',
        ),
        migrations.AddField(
            model_name='esecuzione',
            name='pdfreport',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.pdfreport'),
            preserve_default=False,
        ),
    ]
