# Generated by Django 5.2.4 on 2025-07-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0006_remove_esecuzione_rilevamento_attacco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esecuzione',
            name='pdfreport',
        ),
    ]
