# Generated by Django 5.2.4 on 2025-07-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0006_remove_enciclopediaattacchi_contromisure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esecuzione',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='pdf_reports/'),
        ),
        migrations.DeleteModel(
            name='Pdfreport',
        ),
    ]
