# Generated by Django 5.2.4 on 2025-07-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0007_esecuzione_pdf_report_delete_pdfreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiestaanalisi',
            name='messaggio_sospetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.messaggiosospetto'),
        ),
        migrations.AlterField(
            model_name='richiestaanalisi',
            name='numero_telefonico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.numerotelefonico'),
        ),
    ]
