# Generated by Django 5.2.4 on 2025-07-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0007_esecuzione_pdf_report_delete_pdfreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='rilevamentoattacco',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='pdf_reports/'),
        ),
    ]
