# Generated by Django 5.2.4 on 2025-07-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0008_alter_richiestaanalisi_messaggio_sospetto_and_more'),
        ('enciclopedia', '0008_rilevamentoattacco_pdf_report'),
    ]

    operations = [
    ]
