# Generated by Django 5.2.4 on 2025-07-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0008_esecuzione_pdfreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esecuzione',
            name='pdfreport',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.pdfreport'),
        ),
    ]
