# Generated by Django 5.2.4 on 2025-07-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0009_merge_20250722_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='ruolo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
