# Generated by Django 5.2.4 on 2025-07-21 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0009_alter_esecuzione_pdfreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esecuzione',
            name='pdfreport',
        ),
        migrations.AddField(
            model_name='esecuzione',
            name='RilevamentoAttacco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.rilevamentoattacco'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pdfreport',
        ),
    ]
